# change prefix to Ctrl-a (like in gnu screen)
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# copy mode
unbind [
bind Escape copy-mode
# use mouse in copy mode
set-window-option -g mode-mouse on
set-window-option -g utf8 on

# splitting
unbind %
bind S split-window -h
unbind '"'
bind s split-window -v

# colon :
bind : command-prompt

# let's keep it quiet, ok?
set-option -g visual-activity off
set-option -g visual-bell off
set-option -g visual-content off
set-option -g visual-silence off
set-window-option -g monitor-activity off
set-window-option -g monitor-content ''
set-option -g bell-action none

#Colors
set -g default-terminal "screen-256color"

# History
set-option -g history-limit 1000

# status line
set-option -g status-utf8 on
set-option -g status-justify left
set-option -g status-bg default
set-option -g status-fg green
set-window-option -g window-status-current-fg colour135
set-window-option -g window-status-current-attr underscore
set-option -g status-right '#H #[fg=colour]%I:%M #[fg=colour14]%d.%m.%Y'

# some key-binding changes
bind x kill-pane
bind X next-layout
bind Z previous-layout
unbind Left
bind h select-pane -L
unbind Down
bind j select-pane -D
unbind Up
bind k select-pane -U
unbind Right
bind l select-pane -R
unbind C-Left
bind C-h resize-pane -L
unbind C-Down
bind C-j resize-pane -D
unbind C-Up
bind C-k resize-pane -U
unbind C-Right
bind C-l resize-pane -R
unbind M-Left
bind C-H resize-pane -L 30
unbind M-Down
bind C-J resize-pane -D 30
unbind M-Up
bind C-K resize-pane -U 30
unbind M-Right
bind C-L resize-pane -R 30
