tap "bell-sw/liberica", trusted: true
tap "jetbrains/utils", "https://github.com/JetBrains/homebrew-utils"
tap "jundot/omlx", "https://github.com/jundot/omlx", trusted: true
tap "oven-sh/bun"
brew "atuin"
brew "awscli"
brew "bat"
brew "bottom"
brew "carapace"
brew "cloudflared"
brew "colima"
brew "coreutils"
brew "docker"
brew "docker-compose"
brew "dust"
brew "eza"
brew "fd"
brew "ffmpeg"
brew "fish"
brew "fzf"
brew "gh"
brew "git-delta"
brew "git-xet"
brew "glow"
brew "gost"
brew "grpcurl"
brew "helix"
brew "helm"
brew "jj"
brew "jq"
brew "just"
brew "kubernetes-cli"
brew "lazydocker"
brew "lazygit"
brew "lua-language-server"
brew "marksman"
brew "node@22"
brew "p7zip"
brew "protobuf"
brew "qemu"
brew "ripgrep"
brew "starship"
brew "stern"
brew "stow"
brew "tmux"
brew "trash", link: true
brew "tree-sitter-cli"
brew "uv"
brew "zig"
brew "zls"
brew "zoxide"
brew "jetbrains/utils/kotlin-lsp", trusted: true
brew "jundot/omlx/omlx"
brew "oven-sh/bun/bun", trusted: true
cask "1password-cli"
cask "appcleaner"
cask "font-ibm-plex-mono"
cask "font-symbols-only-nerd-font"
cask "ghostty"
cask "bell-sw/liberica/liberica-jdk21"
cask "bell-sw/liberica/liberica-jdk25"
cask "maccy"
