##################
# Compiler flags #
##################

CHOST="x86_64-pc-linux-gnu"
CFLAGS="-O2 -march=corei7 -pipe"
CXXFLAGS="${CFLAGS}"
FFLAGS="${CFLAGS}"
FCFLAGS="${CFLAGS}"

#############
# USE flags #
#############

# Optimize a bit.
USE="${USE} mmx sse sse2 sse3 ssse3 sse4_1"

# QT/KDE stuff.
USE="${USE} -qt4 -qt3support -kde"

# GTK/GNOME stuff.
USE="${USE} gtk gtk3 -vala introspection -gnome"

# Sound stuff.
USE="${USE} -pulseaudio alsa openal"

# Image stuff.
USE="${USE} png gif jpg tiff gif"

# Video stuff.
USE="${USE} mesa opengl"

# Shell stuff.
USE="${USE} zsh-completion -bash-completion"

# Media stuff.
USE="${USE} gstreamer -vlc v4l ffmpeg vaapi"

# Text stuff.
USE="${USE} pdf djvu"

#Misc
USE="${USE} unicode icu truetype colord nls udev dbus fuse java git ssh -doc"

#################
# Portage flags #
#################
MAKEOPTS="-j9"
ACCEPT_KEYWORDS="~amd64"

########
# Misc #
########
VIDEO_CARDS="intel"
ALSA_CARDS="hda-intel"
LINGUAS="ru en"
INPUT_DEVICES="evdev"

source /var/lib/layman/make.conf

GENTOO_MIRRORS="http://mirror.yandex.ru/gentoo-distfiles/"

SYNC="rsync://rsync2.ru.gentoo.org/gentoo-portage"
