##################
# Compiler flags #
##################

CHOST="x86_64-pc-linux-gnu"
CFLAGS="-O2 -march=corei7 -pipe"
CXXFLAGS="${CFLAGS}"
FFLAGS="${CFLAGS}"
FCFLAGS="${CFLAGS}"

#############
# USE flags #
#############

# Codecs.
USE="${USE} mmx sse sse2 sse3 ssse3 sse4_1 x264 mp3 mpeg2 xvid ffmpeg a52 theora"

# GRAPHICS
USE="${USE} png gif tiff jpeg svg jpeg2k"

# MEDIA
USE="${USE} vaapi alsa gstreamer v4l nsplugin"

# FILESYS
USE="${USE} djvu pdf fuse zip zlib bzip2 gzip lzo lzma"

# DESKTOP
USE="${USE} X mesa opengl consolekit policykit libnotify cairo gtk gtk3 gudev introspection nls icu"

#SYSTEM
USE="${USE} unicode truetype zsh-completion acl colord dbus udev udisks hwdb branding git mercurial ssh"

# PRINT
USE="${USE} cups foomaticdb snmp"

# LANGS
USE="${USE} python java"

# STEAM
USE="${USE} steamruntime"

# BAD
USE ="${USE} -bash-completion -bindist -kmod -doc -qt4 -qt3support -kde -vlc -vala -gnome -pulseaudio"


#################
# Portage flags #
#################
MAKEOPTS="-j9"
ACCEPT_KEYWORDS="~amd64"

########
# XFCE #
########
XFCE_PLUGINS="brightness clock trash"

########
# Misc #
########
VIDEO_CARDS="intel"
ALSA_CARDS="hda-intel"
LINGUAS="ru en"
INPUT_DEVICES="evdev"

source /var/lib/layman/make.conf

GENTOO_MIRRORS="http://mirror.yandex.ru/gentoo-distfiles/"

SYNC="rsync://rsync2.ru.gentoo.org/gentoo-portage"
