PORTDIR="/usr/portage"
DISTDIR="${PORTDIR}/distfiles"
PKGDIR="${PORTDIR}/packages"
##################
# Compiler flags #
##################

CHOST="x86_64-pc-linux-gnu"
CFLAGS="-O2 -march=corei7 -pipe"
CXXFLAGS="${CFLAGS}"
FFLAGS="${CFLAGS}"
FCFLAGS="${CFLAGS}"
LC_MESSAGES=C

#############
# USE flags #
#############

# Codecs.
USE="${USE} mmx sse sse2 sse3 ssse3 sse4_1 x264 opus ffmpeg mp3 mpeg2 xvid a52 theora"

# GRAPHICS
USE="${USE} png svg gif tiff jpeg jpeg2k"

# MEDIA
USE="${USE} vaapi vlc v4l nsplugin"

# FILESYS
USE="${USE} djvu pdf fuse xfs zip zlib bzip2 gzip lzo lzma"

# DESKTOP
USE="${USE} X mesa dri opengl policykit libnotify cairo nls icu qt4 qt5 kde"

#SYSTEM
USE="${USE} unicode openrc truetype zsh-completion acl colord dbus udev udisks hwdb branding ssh"

# PRINT
USE="${USE} cups foomaticdb snmp"

# LANGS
USE="${USE} java"

# VCS
USE="${USE} git mercurial subversion"

# STEAM
USE="${USE} steamruntime"

# BAD
USE ="${USE} -bash-completion -systemd -pulseaudio -bindist -doc -gtk -gtk3 -gnome -vala"


#################
# Portage flags #
#################
MAKEOPTS="-j9"
ACCEPT_KEYWORDS="~amd64"

########
# XFCE #
########
XFCE_PLUGINS="brightness clock trash"

########
# Misc #
########
VIDEO_CARDS="nvidia intel"
ALSA_CARDS="hda-intel"
LINGUAS="ru en"
INPUT_DEVICES="evdev"

source /var/lib/layman/make.conf

GENTOO_MIRRORS="http://mirror.yandex.ru/gentoo-distfiles/"

SYNC="rsync://rsync2.ru.gentoo.org/gentoo-portage"
