add_newline = false

format = """
$directory\
$git_branch\
$git_status\
$character
"""

right_format='$cmd_duration'

[directory]
format = '[ $path ]($style)'
home_symbol = '~'
repo_root_style = 'bold fg:yellow'
style = 'bold blue'
truncate_to_repo = false
truncation_length = 8
truncation_symbol = '…/'

[git_branch]
symbol = ''
style = 'italic'
format = '[ $symbol $branch ]($style)'

[git_status]
style='bold'
format = '[$all_status$ahead_behind ]($style)'

[character]
success_symbol = '[❯](bold green)'
error_symbol = '[✗](bold red) '

[cmd_duration]
min_time = 0
format = ' [$duration]($style) '

