add_newline = false

format = """
$directory\
$character
"""

right_format = """
$git_branch\
$git_status
"""

[directory]
format = '[ $path ]($style)'
home_symbol = '~'
repo_root_style = 'fg:yellow'
style = 'blue'
truncate_to_repo = false
truncation_length = 8
truncation_symbol = '…/'
use_logical_path = false

[git_branch]
symbol = ''
style = 'italic fg:cyan'
format = '[$symbol $branch]($style)'

[git_status]
style = 'fg:cyan'
format = '[$all_status$ahead_behind ]($style)'

[character]
success_symbol = '[❯](bold green)'
error_symbol = '[✗](bold red) '

[cmd_duration]
min_time = 0
format = ' [$duration]($style) '

