theme = "tokyonight_storm"

[editor]
line-number = "relative"
text-width = 100
rulers = [100]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-inlay-hints = true
