PORTDIR="/usr/portage"
DISTDIR="${PORTDIR}/distfiles"
PKGDIR="${PORTDIR}/packages"

##################
# Compiler flags #
##################

CHOST="x86_64-pc-linux-gnu"
CFLAGS="-O2 -march=corei7 -pipe"
CXXFLAGS="${CFLAGS}"
FFLAGS="${CFLAGS}"
FCFLAGS="${CFLAGS}"
LC_MESSAGES=C

#############
# USE flags #
#############

# Formats
USE="${USE} png svg jpeg pdf djvu"

# MEDIA
USE="${USE} v4l vaapi vdpau opengl"

#SYSTEM
USE="${USE} X infinality pulseaudio dbus unicode"

# BAD
USE ="${USE} -openrc -bindist -doc"

#################
# Portage flags #
#################
MAKEOPTS="-j9"
ACCEPT_KEYWORDS="~amd64"

########
# Misc #
########
VIDEO_CARDS="nvidia"
ALSA_CARDS="hda-intel"
LINGUAS="en ru"
INPUT_DEVICES="evdev"
ABI_X86="64 32"

