#!/bin/sh

sxhkd -c $HOME/.config/bspwm/sxhkdrc &
$HOME/.config/bspwm/bar &

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

bspc monitor -d         

bspc config focused_border_color    '#81a2be'
bspc config urgent_border_color     '#cc6666'
