#! /bin/sh

source "$(dirname $0)/config"

style() {
    while [[ $# > 1 ]]; do
        key="$1"

        case $key in
        -B)
            pre_style="${pre_style}%{B$2}"
            post_style="%{B-}${post_style}"
            shift
            ;;
        -F)
            pre_style="${pre_style}%{F$2}"
            post_style="%{F-}${post_style}"
            shift
            ;;
        -U)
            pre_style="${pre_style}%{U$2}"
            post_style="%{U-}${post_style}"
            shift
            ;;
        -A)
            pre_style="${pre_style}%{A:$2:}"
            post_style="%{A}${post_style}"
            shift
            ;;
        -u)
            pre_style="${pre_style}%{+u}"
            post_style="%{-u}${post_style}"
            ;;
        esac
        shift
    done
    echo "${pre_style} $@ ${post_style}"
}

num_mon=$(bspc query -M | wc -l)

while read -r line ; do
	case $line in
		$P_CLOCK*)
			# clock output
            clock=$(style -F $COLOR_STATUS_FG -B $COLOR_STATUS_BG "${line#$P_CLOCK}")
			;;
        $P_KBD_LAYOUT*)
            # keyboard layout
            layout=$(style -A "$E_TOGGLE_KBD" -F $COLOR_STATUS_FG -B $COLOR_STATUS_BG "${line#$P_KBD_LAYOUT}")
            ;;
        W*)
            # bspwm internal state
            wm_desktop=""
            wm_monitor=""
            wm_layout=""
            IFS=':'
            set -- ${line#?}
            while [ $# -gt 0 ] ; do
                item=$1
                name=${item#?}
                echo $name
                case $item in
                    L*)
                        wm_layout="$(style -A "$E_TOGGLE_LAYOUT" -F $COLOR_LAYOUT_FG -B $COLOR_LAYOUT_BG "[${name}]")"
                        ;;
                    M*)
                        if [ $num_mon -gt 1 ] ; then
                            wm_monitor="${wm_monitor}$(style -F $COLOR_ACTIVE_MONITOR_FG -B $COLOR_ACTIVE_MONITOR_BG "${name}")"
                        fi
                        ;;
                    m*)
                        if [ $num_mon -gt 1 ] ; then
                            wm_monitor="${wm_monitor}$(style -F $COLOR_INACTIVE_MONITOR_FG -B $COLOR_INACTIVE_MONITOR_BG "${name}")"
                        fi
                        ;;
                    O*)
                        wm_desktop="${wm_desktop}$(style -F $COLOR_FOCUSED_OCCUPIED_FG -B $COLOR_FOCUSED_OCCUPIED_BG -U $COLOR_FOREGROUND -u "${name}")"
                        ;;
                    F*)
                        wm_desktop="${wm_desktop}$(style -F $COLOR_FOCUSED_FREE_FG -B $COLOR_FOCUSED_FREE_BG -U $COLOR_FOREGROUND -u "${name}")"
                        ;;
                    U*)
                        wm_desktop="${wm_desktop}$(style -F $COLOR_FOCUSED_URGENT_FG -B $COLOR_FOCUSED_URGENT_BG -U $COLOR_FOREGROUND -u "${name}")"
                        ;;
                    o*)
                        wm_desktop="${wm_desktop}$(style -A "$E_TO_DESKTOP${name}" -F $COLOR_OCCUPIED_FG -B $COLOR_OCCUPIED_BG "${name}")"
                        ;;
                    f*)
                        wm_desktop="${wm_desktop}$(style -A "$E_TO_DESKTOP${name}" -F $COLOR_FREE_FG -B $COLOR_FREE_BG "${name}")"
                        ;;
                    u*)
                        wm_desktop="${wm_desktop}$(style -A "$E_TO_DESKTOP${name}" -F $COLOR_URGENT_FG -B $COLOR_URGENT_BG "${name}")"
                        ;;
                esac
                shift
            done
            ;;
	esac
	printf "%s\n" "%{l}${wm_monitor}${wm_layout}%{c}${wm_desktop}%{r}${layout}${clock}"
done
