theme = "kanagawa"

[editor]
mouse = false
text-width = 100
rulers = [100]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-inlay-hints = false

[keys.normal]
'C-a' = "goto_line_start"
'C-e' = "goto_line_end"
'}' = "goto_next_paragraph"
'{' = "goto_prev_paragraph"
'Cmd-c' = "yank_to_clipboard"
'Cmd-s' = ':update'

[keys.normal.space]
'E' = "file_explorer"
'e' = "file_explorer_in_current_buffer_directory"

[keys.select]
'Cmd-c' = "yank_to_clipboard"

[editor.file-picker]
hidden = false
