#!/usr/bin/env bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

hc emit_hook reload

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
Mod=Mod4   

hc keybind Mod4-Mod1-Escape quit
hc keybind $Mod-Shift-Escape reload
hc keybind $Mod-w close
hc keybind $Mod-Return spawn ${TERMINAL:-urxvt} # use your $TERMINAL with xterm as fallback
hc keybind Mod1-F2 spawn rofi -show run

# basic movement
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right

# moving clients
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.05
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle

hc set default_frame_layout 2
hc set_layout max
hc keybind $Mod-g set_layout grid
hc keybind $Mod-m set_layout max
hc keybind $Mod-v set_layout vertical
hc keybind $Mod-h set_layout horizontal

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-Tab         cycle +1
hc keybind $Mod-Shift-Tab   cycle -1

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc attr theme.border_width 3
hc attr theme.active.color '#81a2be'
hc attr theme.normal.color '#454545'
hc attr theme.urgent.color '#cc6666'

hc set frame_border_active_color '#282a2e'
hc set frame_border_width 3
hc set frame_bg_transparent 1
hc set frame_padding 0
hc set frame_gap 15
hc set always_show_frame 0

hc set window_gap 0
hc pad 0 60

# rules
hc unrule -F
hc rule focus=on # normally focus new clients
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# tags
keys=({1..4})
hc rename default 0
for i in {0..3}; do
    hc add "$i"
    key=${keys[$i]}
    hc keybind "$Mod-$key" use_index "$i"
    hc keybind "$Mod-Shift-$key" move_index "$i"
done

# unlock, just to be sure
hc unlock

hsetroot -full $HOME/.config/wallpaper
xsetroot -cursor_name left_ptr

vala-panel & 
